# Generated by Django 3.2.8 on 2021-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='QuestionID'),
        ),
    ]
