# Generated by Django 3.2.8 on 2021-10-18 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(default=uuid.UUID('8ca534ae-5cbe-430c-a4ee-117d04d1a699'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='QuestionID'),
        ),
    ]
