# Generated by Django 3.2.8 on 2021-10-18 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9290a85e-3052-4598-9255-9d901aff4752'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='QuestionID'),
        ),
    ]
