# Generated by Django 3.2.6 on 2021-10-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='questions.question', verbose_name='QuestionID'),
        ),
    ]
