# Generated by Django 3.2.8 on 2021-10-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='UserID'),
        ),
    ]
