# Generated by Django 3.2.8 on 2021-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.CharField(max_length=40, verbose_name='UserID'),
        ),
    ]
