# Generated by Django 3.2.8 on 2021-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_question_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='TagID')),
                ('tag', models.CharField(max_length=30, unique=True, verbose_name='TagName')),
            ],
        ),
    ]
