# Generated by Django 3.2.8 on 2021-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body',
            field=models.TextField(default='nothing', verbose_name='Body'),
            preserve_default=False,
        ),
    ]
