# Generated by Django 3.2.8 on 2021-10-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_answer_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
