# Generated by Django 3.2.8 on 2021-10-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
