# Generated by Django 3.2.8 on 2021-10-20 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20211018_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='ImageID')),
                ('image_path', models.ImageField(upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
