# Generated by Django 3.2.8 on 2021-10-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='image',
        ),
    ]
